OZON_FBS_CALC = {
    "tax_system": "simple",
    "comission_percent": "20",
    "acquiring_percent": "2",
    "shipment_processing": "20",
    "local_index": "1",
    "tax_percent": "15",
    "risk_percent": "3",
    "nonredemption_percentage": "92",
    "profit_percent": "50",
    "cost_per_one": "17.25",
    "count": "4",
    "wage_cost": "10",
    "box_cost": "10",
    "box_size": "11*10*10",
    "nonredemption_processing_cost": "15",
    "last_mile_percent": "5.5",
    "minimal_price_fbs": "123",
    "base_price_fbs": "45",
    "volume_factor_fbs": "25",
    "fix_large_fbs": "1234",
}


OZON_FBO_CALC = {
    "tax_system": "simple",
    "comission_percent": "20",
    "acquiring_percent": "2",
    "shipment_processing": "20",
    "local_index": "1",
    "tax_percent": "15",
    "risk_percent": "3",
    "nonredemption_percentage": "92",
    "profit_percent": "50",
    "cost_per_one": "17.25",
    "count": "4",
    "wage_cost": "10",
    "box_cost": "10",
    "box_size": "11*10*10",
    "nonredemption_processing_cost": "15",
    "last_mile_percent": "5.5",
    "base_price_fbo": "123",
    "volume_factor_fbo": "123",
    "fix_large_fbo": "123",
}


OZON_FBS_BULK_CALC = [
    {
        "tax_system": "simple",
        "comission_percent": "20",
        "acquiring_percent": "2",
        "shipment_processing": "20",
        "local_index": "1",
        "tax_percent": "15",
        "risk_percent": "3",
        "nonredemption_percentage": "92",
        "profit_percent": "50",
        "cost_per_one": "17.25",
        "count": "4",
        "wage_cost": "10",
        "box_cost": "10",
        "box_size": "11*10*10",
        "nonredemption_processing_cost": "15",
        "last_mile_percent": "5.5",
        "minimal_price_fbs": "123",
        "base_price_fbs": "45",
        "volume_factor_fbs": "25",
        "fix_large_fbs": "1234",
    },
    {
        "tax_system": "simple",
        "comission_percent": "20",
        "acquiring_percent": "2",
        "shipment_processing": "20",
        "local_index": "1",
        "tax_percent": "15",
        "risk_percent": "3",
        "nonredemption_percentage": "92",
        "profit_percent": "50",
        "cost_per_one": "17.25",
        "count": "4",
        "wage_cost": "10",
        "box_cost": "10",
        "box_size": "11*10*10",
        "nonredemption_processing_cost": "15",
        "last_mile_percent": "5.5",
        "minimal_price_fbs": "123",
        "base_price_fbs": "45",
        "volume_factor_fbs": "25",
        "fix_large_fbs": "1234",
    },
]


OZON_FBO_BULK_CALC = [
    {
        "tax_system": "simple",
        "comission_percent": "20",
        "acquiring_percent": "2",
        "shipment_processing": "20",
        "local_index": "1",
        "tax_percent": "15",
        "risk_percent": "3",
        "nonredemption_percentage": "92",
        "profit_percent": "50",
        "cost_per_one": "17.25",
        "count": "4",
        "wage_cost": "10",
        "box_cost": "10",
        "box_size": "11*10*10",
        "nonredemption_processing_cost": "15",
        "last_mile_percent": "5.5",
        "base_price_fbo": "123",
        "volume_factor_fbo": "123",
        "fix_large_fbo": "123",
    },
    {
        "tax_system": "simple",
        "comission_percent": "20",
        "acquiring_percent": "2",
        "shipment_processing": "20",
        "local_index": "1",
        "tax_percent": "15",
        "risk_percent": "3",
        "nonredemption_percentage": "92",
        "profit_percent": "50",
        "cost_per_one": "17.25",
        "count": "4",
        "wage_cost": "10",
        "box_cost": "10",
        "box_size": "11*10*10",
        "nonredemption_processing_cost": "15",
        "last_mile_percent": "5.5",
        "base_price_fbo": "123",
        "volume_factor_fbo": "123",
        "fix_large_fbo": "123",
    },
]


OZON_LOG_FBS_CALC = {
    "box_size": "125*125*125",
    "local_index": "1",
    "minimal_price_fbs": "10",
    "base_price_fbs": "10",
    "volume_factor_fbs": "10",
    "fix_large_fbs": "102",
}


OZON_LOG_FBO_CALC = {
    "box_size": "125*125*99",
    "local_index": "1.5",
    "base_price_fbo": "123",
    "volume_factor_fbo": "123",
    "fix_large_fbo": "123",
}


OZON_RETURNS_FBS_CALC = {
    "box_size": "125*125*125",
    "nonredemption_percentage": "92",
    "local_index": "1",
    "minimal_price_fbs": "10",
    "base_price_fbs": "10",
    "volume_factor_fbs": "10",
    "fix_large_fbs": "102",
}


OZON_RETURNS_FBO_CALC = {
    "box_size": "125*125*99",
    "nonredemption_percentage": "1.5",
    "local_index": "1.8",
    "base_price_fbo": "123",
    "volume_factor_fbo": "123",
    "fix_large_fbo": "123",
}
